function t = generateTimeVector(Fs, T)   
%This MATLAB function generateTimeVector creates a time vector t based on two input parameters: Fs and T.
%Fs: This parameter represents the sampling frequency, which is the number of samples per unit of time. It determines how many data points are captured per second. A higher sampling frequency provides more detail but also requires more storage and processing power.
%T: This parameter represents the duration of the time vector in seconds. It specifies the total length of time covered by the generated time vector.
%The function calculates the time vector t using the following steps:
%It starts from time 0.
%It increments the time by 1/Fs until it reaches T - 1/Fs.
%The increment value 1/Fs represents the time interval between consecutive samples. It's the reciprocal of the sampling frequency, indicating the time duration between two successive samples.
%The time vector t generated by this function will have T*Fs + 1 elements. This is because it starts from 0 and ends at T - 1/Fs, inclusive. Each element of t corresponds to a specific point in time, spaced apart by 1/Fs seconds.










% Generate time vector
    t = 0 : 1/Fs : T - 1/Fs;
end